
import os
import glob
from datetime import datetime

# Version 2.0 - Fixed CSS curly brace issue with f-strings
CHARTS_DIR = 'charts'
OUTPUT_FILE = 'index.html'

def create_dashboard():
    # Check if charts directory exists
    if not os.path.exists(CHARTS_DIR):
        print(f"Charts directory not found: {CHARTS_DIR}")
        return

    # Get all png files
    chart_files = glob.glob(os.path.join(CHARTS_DIR, '*.png'))
    chart_files.sort()

    if not chart_files:
        print("No charts found.")
        charts_html = "<p style='text-align:center; width:100%;'>No charts available yet.</p>"
    else:
        charts_html = ""
        for file_path in chart_files:
            # Get filename for display
            filename = os.path.basename(file_path)
            # Remove extension for title
            title = os.path.splitext(filename)[0].replace('_', ' ')
            
            # Create HTML block for this chart using relative path
            relative_path = f"charts/{filename}"
            
            charts_html += f"""
            <div class="chart-card">
                <h3>{title}</h3>
                <a href="{relative_path}" target="_blank">
                    <img src="{relative_path}" alt="{title}" loading="lazy">
                </a>
            </div>
            """

    # Generate full HTML
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S KST")
    
    # Build HTML without using .format() to avoid curly brace conflicts
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Market Data Dashboard</title>
    <style>
        :root {{
            --bg-color: #1a1a1a;
            --card-bg: #2d2d2d;
            --text-color: #e0e0e0;
            --accent-color: #4a90e2;
        }}

        body {{
            font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            margin: 0;
            padding: 20px;
        }}

        header {{
            text-align: center;
            margin-bottom: 40px;
            padding: 20px 0;
            border-bottom: 1px solid #333;
        }}

        h1 {{
            margin: 0;
            font-size: 2.5rem;
            color: var(--text-color);
        }}

        .last-updated {{
            margin-top: 10px;
            color: #888;
            font-style: italic;
        }}

        .dashboard-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(600px, 1fr));
            gap: 20px;
            max-width: 1600px;
            margin: 0 auto;
        }}

        @media (max-width: 768px) {{
            .dashboard-grid {{
                grid-template-columns: 1fr;
            }}
        }}

        .chart-card {{
            background-color: var(--card-bg);
            border-radius: 12px;
            padding: 15px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
            transition: transform 0.2s ease;
            text-align: center;
        }}

        .chart-card:hover {{
            transform: translateY(-5px);
        }}

        .chart-card h3 {{
            margin-top: 0;
            margin-bottom: 15px;
            font-size: 1.2rem;
            color: #ccc;
        }}

        .chart-card img {{
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }}

        footer {{
            text-align: center;
            margin-top: 50px;
            color: #666;
            font-size: 0.9rem;
        }}
    </style>
</head>
<body>
    <header>
        <h1>📊 Market Data Dashboard</h1>
        <div class="last-updated">Last Updated: {now}</div>
    </header>

    <div class="dashboard-grid">
        {charts_html}
    </div>

    <footer>
        <p>Auto-generated by Antigravity Agent</p>
    </footer>
</body>
</html>
"""

    # Write to file
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"Dashboard generated: {OUTPUT_FILE}")

if __name__ == "__main__":
    create_dashboard()
